---
- hosts: nodes
  become: yes
  
  tasks:
    - name: Include ansible_personal role.
      include_role:
        name: ansible_personal
      tags: personal

    - name: Include ansible_jenkins role.
      include_role:
        name: ansible_jenkins
      tags: jenkins

    - name: Include ansible_flask role.
      include_role:
        name: ansible_flask
      tags: flask

    - name: Include ansible_server role.
      include_role:
        name: ansible_server
      tags: server
