# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  servers=[
    {
      :boxname  => "flask",
      :hostname => "flask.lab",
      :ip       => "192.168.56.62",
      :box      => "almalinux/9",
      :key      => "/vagrant/vg_box.pub",
      :ram      => "2048",
      :cpu      => 1
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", 
	                 ip: machine[:ip],
                   name: "vboxnet0"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = machine[:boxname]
        vb.gui = false
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]

      node.vm.provision "shell" do |s|
	    s.inline = "cat $1 >> /home/vagrant/.ssh/authorized_keys"
        s.args = machine[:key] 
      end
    end
  end
end
end

