---
- name: Install Docker.
  pacman:
    name: docker
    state: present

- name: Enable Docker service.
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group.
  user:
    name: "{{ user }}"
    groups: docker
