---
- name: Install Docker and Docker Compose.
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable Docker service.
  service:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group.
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
