---
- hosts: localhost
  become: yes
  vars:
    - user: 'labbrat'
    - bashrc: "/home/{{ user }}/.zshrc"

  tasks:
    - name: Install stuff.
      pacman:
        name: '{{ item }}'
        state: present
      with_items:
        - vim
        - git
        - openconnect
        - transmission-gtk
        - python-virtualenv
        - python-pip

    - name: Install Ansible.
      pip:
        name: "{{ item }}"
        extra_args: --user
      with_items:
        - ansible 
      become_user: "{{ user }}"

    - name: Ensure that custom alias information line is present.
      lineinfile:
        name: "{{ bashrc }}"
        line: "######## Custom Aliases Created By Ansible ########"
        state: present
      check_mode: yes
      register: custom_alias_notify

    - name: Add alias title.
      lineinfile:
        path: "{{ bashrc }}"
        line: "\n######## Custom Aliases Created By Ansible ########"
      when: custom_alias_notify is changed
 
    - name: Add aliases and PATH to bashrc.
      lineinfile:
        path: "{{ bashrc }}"
        line: "{{ item }}"
      loop:
        - export scripts="/home/{{ user }}/scripts"
        - export pip_path="/home/{{ user }}/.local/bin"
        - export PATH=$PATH:$scripts:$pip_path
        - alias sv='source venv/bin/activate'
        - alias ga="git add"
        - alias gc="git commit -m"
        - alias gp="git push"
        - alias gs="git status"
        - alias gh="git config user.email 'xoovoox@protonmail.com' && git config user.name 'Lab-Brat'"
      when: custom_alias_notify is changed
