---
- hosts: localhost
  become: yes
  vars:
    - user: 'labbrat'
    - repo_lsd: 'https://api.github.com/repos/Peltoche/lsd/releases/latest'
    - grep_lsd: 'browser_download_url.*lsd_.*_amd64.deb'
    - bashrc: "/home/{{ user }}/.bashrc_test"

  tasks:
    - name: Get latest lsd link.
      shell: curl -s "{{ repo_lsd }}" | grep "{{ grep_lsd }}" | awk -F '"' '{print $4}'
      register: lsd_link

    - name: Download and install lsd deb package.
      apt:
        deb: "{{ lsd_link.stdout_lines[0] }}"

    - name: Install other software.
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - vim
        - git
        - openconnect
        - python3-venv
        - python3-pip

    - name: Install Ansible.
      pip:
        name: "{{ item }}"
        extra_args: --user
      with_items:
        - ansible 
      become_user: "{{ user }}"

    - name: Ensure that custom alias information line is present.
      lineinfile:
        name: "{{ bashrc }}"
        line: "######## Custom Aliases Created By Ansible ########"
        state: present
      check_mode: yes
      register: custom_alias_notify

    - name: Add alias title.
      lineinfile:
        path: "{{ bashrc }}"
        line: "\n######## Custom Aliases Created By Ansible ########"
      when: custom_alias_notify is changed
 
    - name: Add aliases and PATH to bashrc.
      lineinfile:
        path: "{{ bashrc }}"
        line: "{{ item }}"
      loop:
        - export scripts="/home/{{ user }}/scripts"
        - export PATH=$PATH:$scripts
        - export pip_path="/home/{{ user }}/.local/bin"
        - export PATH=$PATH:$pip_path
        - alias py=python3
        - alias gt="git add . && git commit -m $CMT && git push
