---
- name: Install commands with package manager.
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - bat

- name: Ensure that custom alias information line is there.
  lineinfile:
    name: "{{ bashrc }}"
    line: "######## Custom Aliases Created By Ansible ########"
    state: present
  check_mode: yes
  register: custom_alias_notify

- name: Add alias title.
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    line: "\n######## Custom Aliases Created By Ansible ########"
  when: custom_alias_notify is changed

- name: Add alias to bat.
  ansible.builtin.lineinfile:
    path: "{{ bashrc }}"
    line: "alias cat=bat"
