---
- name: Install docker-compose.
  dnf:
    name: 'docker-compose'
    state: present

- name: Create directory for compose file.
  ansible.builtin.file:
    path: "{{ src_jenkins }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yaml to remote host.
  ansible.builtin.copy:
    src: "{{ src_compose }}" 
    dest: "{{ src_jenkins }}"
    mode: '0644'

- name: Wait 5 seconds for the container to start.
  pause:
    seconds: 5

- name: Launch docker-compose.
  community.docker.docker_compose:
    project_src: "{{ src_jenkins }}"

- name: Print initial admin password.
  command: cat "{{ init_pass }}" 
  register: pass_out

- debug: msg="{{ pass_out.stdout }}"
